---
title: "Making cheese"
output: 
    rmarkdown::html_vignette
vignette: >
    %\VignetteIndexEntry{Functions in the cheese package}
    %\VignetteEngine{knitr::rmarkdown}
    \usepackage[utf8]{inputenc}
---

Structuring code that is robust to updates in the data, changes in methodological specfications, etc., and can get to presentation-ready results in an automated way can mitigate errors caused by painful, tedious tasks--it can also be a huge time saver. The `cheese` package was designed with this philosophy in mind, heavily influenced by (and explicit dependencies on) [`tidy`](https://www.tidyverse.org/) concepts. Its intention is to provide general tools for working with data and results during statistical analysis, in addition to a collection of functions designated for specific statistical tasks. Let's take a closer look:

### Heart disease
The dataset used throughout this tutorial comes from the [UCI Machine Learning Repository](http://archive.ics.uci.edu/ml/datasets/Heart+Disease). Details of the pre-processing steps of the raw data to what is found within the package can be found on the package's Github site [here](https://github.com/zajichek/cheese/blob/master/data-raw/heart_disease.R).

```{r}
#Load the package
require(cheese)

#Look at the data
heart_disease

```

